name: Daily Progress
on:
#   workflow_dispatch
  schedule:
    - cron: '7 4 * * *' # runs every day at 3.40 pm EST
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update README
        run: |
          # Get the current day of the year
          DAY_OF_YEAR=$(date +%j)
          # Calculate the progress percentage
          PROGRESS=$(echo "scale=2; ($DAY_OF_YEAR / 365) * 100" | bc)
          # Generate the progress bar
          PROGRESS_BAR="["
          for i in $(seq 1 20); do
            if [ $(echo "$PROGRESS > ($i * 5)" | bc) -eq 1 ]; then
              PROGRESS_BAR="${PROGRESS_BAR}#"
            else
              PROGRESS_BAR="${PROGRESS_BAR}-"
            fi
          done
          PROGRESS_BAR="${PROGRESS_BAR}] ${PROGRESS}%"
          # Replace the progress bar in the README file
          sed -i "s/^Progress.*$/Progress: ${PROGRESS_BAR}/" README.md
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "Daily update" || true
          git push origin HEAD:main
