name: Daily Progress
on:
  schedule:
    - cron: "45 23 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update README
        run: |
          # Get the current day of the year
          DAY_OF_YEAR=$(date +%j)
          # Calculate the progress percentage
          PROGRESS=$(echo "scale=2; ($DAY_OF_YEAR / 365) * 100" | bc)
          # Generate the progress bar
          PROGRESS_BAR="["
          for i in $(seq 1 20); do
            if [ $(echo "$PROGRESS > ($i * 5)" | bc) -eq 1 ]; then
              PROGRESS_BAR="${PROGRESS_BAR}#"
            else
              PROGRESS_BAR="${PROGRESS_BAR}-"
            fi
          done
          PROGRESS_BAR="${PROGRESS_BAR}] ${PROGRESS}%"
          # Print the progress bar
          echo "Updating README..."
          for i in $(seq 0 19); do
            printf ' '
            sleep 0.1
          done
          echo
          # Replace the progress bar in the README file
          sed -i "s/^Progress.*$/Progress: ${PROGRESS_BAR}/" README.md
          # Commit the changes
          git config --local user.email "jambhale.shubham9@gmail.com"
          git config --local user.name "Shubham-Jambhale"
          git commit -a -m "Daily update" || true
          git push origin HEAD:main
      - name: Add code to README
        run: |
          echo "Today's date: $(date +%d-%m-%Y)" >> README.md
          echo "Today's progress: ${PROGRESS}%" >> README.md
      - name: Commit changes
        run: |
          git config --local user.email "jambhale.shubham9@gmail.com"
          git config --local user.name "Shubham-Jambhale"
          git commit -a -m "Added today's date and progress to README" || true
          git push origin HEAD:main
      - name: Update progress bar
        run: |
          while true; do
            sleep 300 # 5 minutes
            PROGRESS=$(echo "scale=2; ($DAY_OF_YEAR / 365) * 100" | bc)
            PROGRESS_BAR="["
            for i in $(seq 1 20); do
              if [ $(echo "$PROGRESS > ($i * 5)" | bc) -eq 1 ]; then
                PROGRESS_BAR="${PROGRESS_BAR}#"
              else
                PROGRESS_BAR="${PROGRESS_BAR}-"
              fi
            done
            PROGRESS_BAR="${PROGRESS_BAR}] ${PROGRESS}%"
            echo "Progress: ${PROGRESS_BAR}"
          done
